-- ==============================================================================
-- Stage 0: Relational Architecture - OLTP Financial Schema
-- Giai đoạn 0: Kiến trúc Quan hệ - Lược đồ OLTP cho Tài chính
-- ==============================================================================

-- 1. Create a dedicated Tablespace for Financial Data
-- Tạo một Tablespace riêng biệt cho dữ liệu tài chính
CREATE TABLESPACE ts_financial_data
    DATAFILE 'financial_data_01.dbf' SIZE 10G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    SEGMENT SPACE MANAGEMENT AUTO;

-- 2. Create the Customers Table
-- Tạo bảng Khách hàng
CREATE TABLE customers (
    customer_id     NUMBER GENERATED ALWAYS AS IDENTITY, -- Auto-increment identity column
    national_id     VARCHAR2(50) NOT NULL,
    full_name       VARCHAR2(200) NOT NULL,
    customer_type   VARCHAR2(20) NOT NULL, -- 'RETAIL', 'CORPORATE'
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    --
    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT uq_customers_nat_id UNIQUE (national_id),
    CONSTRAINT chk_cust_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    CONSTRAINT chk_cust_type CHECK (customer_type IN ('RETAIL', 'CORPORATE'))
) 
TABLESPACE ts_financial_data
PCTFREE 10; -- OLTP setup: Reserve 10% of block for future updates (Ngừa phân mảnh khối)

-- 3. Create the Accounts Table
-- Tạo bảng Tài khoản
CREATE TABLE accounts (
    account_id      NUMBER GENERATED ALWAYS AS IDENTITY,
    customer_id     NUMBER NOT NULL,
    account_number  VARCHAR2(30) NOT NULL,
    currency_code   VARCHAR2(3) DEFAULT 'USD' NOT NULL,
    balance         NUMBER(18, 4) DEFAULT 0 NOT NULL,
    is_locked       NUMBER(1) DEFAULT 0 NOT NULL, -- 0: False, 1: True
    opened_date     DATE DEFAULT SYSDATE NOT NULL,
    --
    CONSTRAINT pk_accounts PRIMARY KEY (account_id),
    CONSTRAINT uq_account_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_cust FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT chk_acc_locked CHECK (is_locked IN (0, 1))
)
TABLESPACE ts_financial_data
PCTFREE 20; -- Balance updates frequently, reserve more space (Dự phòng nhiều dung lượng hơn cho các bản cập nhật số dư liên tục)

-- Indexes for Foreign Keys (Crucial in Oracle to prevent Table Locks during Parent Delete)
-- Chỉ mục cho Khóa ngoại (Rất quan trọng trong Oracle để ngăn chặn việc Khóa toàn bảng khi xóa dữ liệu bảng cha)
CREATE INDEX idx_accounts_cust_id ON accounts(customer_id) TABLESPACE ts_financial_data;

-- 4. Create the Transactions Table
-- Tạo bảng Giao dịch
CREATE TABLE transactions (
    transaction_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    from_account_id     NUMBER,
    to_account_id       NUMBER,
    amount              NUMBER(18, 4) NOT NULL,
    transaction_type    VARCHAR2(30) NOT NULL, -- 'TRANSFER', 'DEPOSIT', 'WITHDRAWAL'
    transaction_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status              VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL,
    --
    CONSTRAINT pk_transactions PRIMARY KEY (transaction_id),
    CONSTRAINT fk_tx_from_acc FOREIGN KEY (from_account_id) REFERENCES accounts(account_id),
    CONSTRAINT fk_tx_to_acc FOREIGN KEY (to_account_id) REFERENCES accounts(account_id),
    CONSTRAINT chk_tx_amount CHECK (amount > 0), -- Amount must be positive (Số tiền phải dương)
    CONSTRAINT chk_tx_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REVERSED'))
)
TABLESPACE ts_financial_data
PCTFREE 5; -- Transactions are insert-only, rarely updated. Lower PCTFREE saves space. 
           -- (Giao dịch thường chỉ chèn thêm, ít cập nhật. Giảm PCTFREE giúp tiết kiệm dung lượng.)

CREATE INDEX idx_tx_from_acc ON transactions(from_account_id) TABLESPACE ts_financial_data;
CREATE INDEX idx_tx_to_acc ON transactions(to_account_id) TABLESPACE ts_financial_data;
CREATE INDEX idx_tx_date ON transactions(transaction_date) TABLESPACE ts_financial_data;

-- ==============================================================================
-- Summary (Tổng kết):
-- 1. Used IDENTITY columns (Oracle 12c+) instead of manual Sequences.
-- 2. Heavy use of CHECK constraints to enforce data integrity.
-- 3. Tuned PCTFREE based on update patterns (10% for mixed, 20% for heavy updates, 5% for insert-only).
-- 4. Indexed all Foreign Keys to prevent locking issues.
-- ==============================================================================
