{
 "title": "Oracle DB System Performance",
 "tags": [
  "oracle",
  "infrastructure"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Database Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporter Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"oracle-production\"}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_sessions{status=\"ACTIVE\"}"
    }
   ]
  },
  {
   "title": "Database Sessions Profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "oracledb_sessions", "legendFormat": "{{status}} Sessions" }
   ]
  },
  {
   "title": "Physical Read/Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(oracledb_physical_reads_total[1m])",
     "legendFormat": "Physical Reads"
    },
    {
     "expr": "rate(oracledb_physical_writes_total[1m])",
     "legendFormat": "Physical Writes"
    }
   ]
  }
 ]
}