-- ==============================================================================
-- Stage 3: Performance Engineering - Reverse Key Index
-- Giai đoạn 3: Kỹ thuật Hiệu suất - Chỉ mục khóa đảo ngược
-- ==============================================================================

-- In a massive OLTP system, you might have an `orders` table.
-- The Primary Key is `order_id` (generated by sequence/identity).
-- (Trong hệ thống OLTP lớn, Khóa chính tự động tăng).

-- Example sequence inserts: 1001, 1002, 1003, 1004...
-- In a standard B-Tree Index, all of these values go to the exact same "Right-most leaf block".
-- If you have 50 parallel application threads inserting orders simultaneously,
-- all 50 threads will fight over the exact same physical block in memory.
-- This causes a massive wait event called: "buffer busy waits".
-- (50 luồng chạy song song sẽ tranh giành nhau CÙNG MỘT khối vật lý trên nhánh phải nhất của cây B-Tree, gây ra hiện tượng buffer busy waits).

-- Solution: Reverse Key Index
-- It physically reverses the bytes before storing them in the index:
-- 1001 -> 1001
-- 1002 -> 2001
-- 1003 -> 3001
-- 1004 -> 4001
-- Now, the inserts are scattered across completely different leaf blocks in the B-Tree.
-- No more contention!
-- (Bây giờ dữ liệu chèn được phân tán ngẫu nhiên khắp B-Tree. Hết tình trạng tranh chấp nghẽn cổ chai).

CREATE TABLE massive_orders (
    order_id NUMBER NOT NULL,
    order_date TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Creating a Reverse Key Index
CREATE UNIQUE INDEX idx_orders_rev ON massive_orders(order_id) REVERSE;

-- Drawback (Nhược điểm):
-- Because the numbers are physically scattered, you can NO LONGER do Index Range Scans.
-- "SELECT * FROM massive_orders WHERE order_id BETWEEN 1000 AND 1010" 
-- will require a Full Table Scan.
-- It is strictly used for Exact Match Lookups (order_id = 1001) in high-insert OLTP.
-- (Chỉ dùng cho Truy vấn khớp chính xác ở hệ thống OLTP chèn siêu tốc. Không thể dùng Range Scan `BETWEEN`).
