apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/oracle"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-data-oracle-db-0 # Matches StatefulSet volume claim template naming
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    rows:
    requests:
      storage: 50Gi
